version: "3.8"
services:
  notification-db-dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - JASYPT_ENCRYPTOR_PASSWORD=SuperS3ecr3etZ
    hostname: notification-db-dev
    ports:
      - '8080:8080'
    env_file:
      - ./notification-db-dev.env

networks:
  default:
    external:
      name: notification-system-network