version: "3.8"
services:
  notification-db-prod:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    hostname: notification-db-prod
    ports:
      - '80:80'
    env_file:
      - ./notification-db-prod.env

networks:
  default:
    external:
      name: notification-system-network